version: 0.2

phases:
    install:
        commands:
            - echo no installation is required
    build:
        commands:
            - echo Build started on `date`
            - aws cloudformation validate-template --template-body file://CreateRole.yml --region=us-east-1  --capabilities CAPABILITY_IAM
    post_build:
         commands:
            - aws cloudformation deploy --stack-name createRole --template-file CreateRole.yml --region=us-east-1  --capabilities CAPABILITY_IAM
            - echo Build completed on `date`
artifacts:
  paths:
    - '*'