Description: >
    This file needs to be called by buildspec.yml
Resources:
    SampleManagedPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
          Name: codebuildpolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Sid: AllowAllUsersToListAccounts
                Effect: Allow
                Action:
                  - iam:ListAccountAliases
                  - iam:ListUsers
                  - iam:GetAccountSummary
                Resource: "*"
    CodeBuildRole:
        Type: 'AWS::IAM::Role'
        Properties:
          Name : codebuildrole
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - ec2.amazonaws.com
                Action:
                  - 'sts:AssumeRole'
          Path: /
          ManagedPolicyArns:
            - !Ref codebuildpolicy